/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.github.gearhand.roguetraderscalafx

import net.jcazevedo.moultingyaml._

import scala.collection.Map



object App {
  def main(args: Array[String]): Unit = {
    println(greeting())

  }

  def greeting(): String = "Hello, world!"
}
