/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.github.gearhand.roguetraderscalafx

import com.github.gearhand.roguetraderscalafx.MyYamlProtocol.EssentialsCatalogFormat
import net.jcazevedo.moultingyaml._

import scala.io.Source



object App {
  def main(args: Array[String]): Unit = {
    println(greeting())

    println(System.getProperty("user.dir"))
    val source = Source.fromFile("src/test/resources/essentials.yml", "utf-8")
    val yamlAst = try
      EssentialsCatalogFormat.read(source.getLines().mkString("\n").parseYaml)
    finally source.close()
  }

  def greeting(): String = "Hello, world!"
}
